### ISSUE TITLE
vertical alignment does not appear to be fixed

### ISSUE THREAD

**Issue by ClmnsRck** [SwiftUIKit/Marquee#1]
I have this code:
```
VStack(alignment: .leading) {
                Marquee {
                    Text("Tag \(viewModel.courseDay.indexRank) - \(viewModel.courseDay.title ?? "KEIN TITEL GEGEBEN!")") //TODO: add marqueeText to entire app
                        .font(.headline)
                        .fontWeight(.semibold)
                        .foregroundColor(.primary)
                }.marqueeDuration(9)
                
                Text(viewModel.courseDay.description ?? "")
                    .font(.body)
                    .fontWeight(.light)
                    .foregroundColor(.secondary)
            }
            .padding(.all, 16)
```
This however causes the text to be shifted downwards ...
<img width="395" alt="Screenshot 2021-05-02 at 11 45 17" src="https://user-images.githubusercontent.com/18589489/116808948-f498b200-ab3b-11eb-9a64-7c33cf32d3d0.png">

**Comment by CatchZeng** [comment]
I have already tried and found no problems, please provide more information.

![Screen Shot 2021-05-07 at 2 32 29 PM](https://user-images.githubusercontent.com/10027281/117407391-11205a00-af41-11eb-93fe-a322c5473a30.png)

**Comment by kelada** [comment]
Hi @CatchZeng I've run into this alignment issue when using the `.marqueeWhenNotFit(..)` modifier (see screenshot below).

![image](https://user-images.githubusercontent.com/30747386/123955668-26968b00-d9aa-11eb-8177-0d84d422159e.png)

I'm new to your library so it's possible that I'm using it incorrectly. Any help would be appreciated (see source below).

```
import SwiftUI
import Marquee

struct ContentView: View {
    var body: some View {
        VStack(alignment: .center) {
            Text("This works")
            Marquee {
                Text("This does not work")
            }
            .frame(height: 20)
            .marqueeWhenNotFit(true)
        }.padding()
    }
}

struct ContentView_Previews: PreviewProvider {
    static var previews: some View {
        ContentView()
    }
}
```

**Comment by CatchZeng** [comment]
@kelada For the feature of marqueeWhenNotFit, you can see
https://stackoverflow.com/a/65197021/14785930

**Comment by kelada** [comment]
> @kelada For the feature of marqueeWhenNotFit, you can see
> https://stackoverflow.com/a/65197021/14785930

@CatchZeng thanks for the quick reply. I don't quite understand your answer, as I am aware of what `.marqueeWhenNotFit(...)` does and am using it for a reason - in my previous comment I'm highlighting that the `Marquee` does not respect the `VStack(alignment: .center) { ... }`.

What I am trying to do is centre a Text view when the string fits inside the Marquee, if it doesn't fit, it should animate - the key is that it respects the alignment of the `VStack` when not animating.

I've been looking into seeing if I can work around this by using an `.alignmentGuide(...)` modifier, but the behaviour is very inconsistent.
https://swiftui-lab.com/alignment-guides/

**Comment by CatchZeng** [comment]
> > @kelada For the feature of marqueeWhenNotFit, you can see
> > https://stackoverflow.com/a/65197021/14785930
> 
> @CatchZeng thanks for the quick reply. I don't quite understand your answer, as I am aware of what `.marqueeWhenNotFit(...)` does and am using it for a reason - in my previous comment I'm highlighting that the `Marquee` does not respect the `VStack(alignment: .center) { ... }`.
> 
> What I am trying to do is centre a Text view when the string fits inside the Marquee, if it doesn't fit, it should animate - the key is that it respects the alignment of the `VStack` when not animating.
> 
> I've been looking into seeing if I can work around this by using an `.alignmentGuide(...)` modifier, but the behaviour is very inconsistent.
> https://swiftui-lab.com/alignment-guides/

Is the picture shown below what you want?

![marquee](https://user-images.githubusercontent.com/10027281/124214721-42726c00-db25-11eb-8f6e-be893c3ca2d9.gif)

You can upgrade marqueue to `0.3.0` and try the code below.

```swift
        VStack(alignment: .center) {
            Text("This works")
            Marquee {
                Text("This also works")
                    .background(Color.yellow)
            }.background(Color.blue)
            .frame(height: 20)
            // This is the key point.
            .marqueeIdleAlignment(.center)
            .marqueeWhenNotFit(true)
        }.padding()
```

**Comment by kelada** [comment]
@CatchZeng that's perfect! thank you so much! 🥇
